

// TOOL:     vlog2tf
// DATE:     Mon Jun 02 22:25:32 2014
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   determineNum
// DESIGN:   determineNum
// FILENAME: determineNum_tf.v
// PROJECT:  Unknown
// VERSION:  2.0
// This file is auto generated by the Diamond


`timescale 1 ns / 1 ns

// Define Module for Test Fixture
module determineNum_tf();

// Inputs
    reg [2:0] sel;
    reg [7:0] ADCData;
    reg reset_n;


// Outputs
    wire [3:0] dispNum;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    determineNum UUT (
        .sel(sel), 
        .ADCData(ADCData), 
        .reset_n(reset_n), 
        .dispNum(dispNum)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
		
		//0, 1, 3, 4
            sel = 0;
            ADCData = 255;
            reset_n = 1;
		#10 reset_n = 0;
		#10 reset_n = 1;
		#40 sel = 1;
		#40 sel = 3;
		#40 sel = 4;
		#40 sel = 2; //Out of bounds
    end

endmodule // determineNum_tf