

// TOOL:     vlog2tf
// DATE:     Wed Jun 04 17:56:45 2014
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   Sec6_Top
// DESIGN:   Sec6_Top
// FILENAME: Sec6_Top_tf.v
// PROJECT:  Unknown
// VERSION:  2.0
// This file is auto generated by the Diamond


`timescale 1 ms / 1 ms

// Define Module for Test Fixture
module Sec6_Top_tf();

// Inputs
    reg [7:0] ADCData;
    reg reset_n;


// Outputs
    wire [2:0] sel;
    wire [6:0] segments;
    wire CS_n;
    wire RD_n;
    wire WR_n;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    Sec6_Top UUT (
        .ADCData(ADCData), 
        .reset_n(reset_n), 
        .sel(sel), 
        .segments(segments), 
        .CS_n(CS_n), 
        .RD_n(RD_n), 
        .WR_n(WR_n)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
           ADCData = 174;
            reset_n = 1;
			
		#20 reset_n = 0;
		#20 reset_n = 1;
		#1000 ADCData = 200;
    end

endmodule // Sec6_Top_tf