

// TOOL:     vlog2tf
// DATE:     Mon Jun 02 22:24:34 2014
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   sevenSeg
// DESIGN:   sevenSeg
// FILENAME: sevenSeg_tf.v
// PROJECT:  Unknown
// VERSION:  2.0
// This file is auto generated by the Diamond


`timescale 1 ns / 1 ns

// Define Module for Test Fixture
module sevenSeg_tf();

// Inputs
    reg [3:0] data;


// Outputs
    wire [6:0] segments;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    sevenSeg UUT (
        .data(data), 
        .segments(segments)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            data = 0;
    end

endmodule // sevenSeg_tf