

// TOOL:     vlog2tf
// DATE:     Tue May 13 00:00:57 2014
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   Lolhi
// DESIGN:   Lolhi
// FILENAME: Lolhi_tf.v
// PROJECT:  Unknown
// VERSION:  2.0
// This file is auto generated by the Diamond


`timescale 1 ns / 1 ns

// Define Module for Test Fixture
module Lolhi_tf();

// Inputs
    reg A;
    reg B;
    reg C;
    reg AnalogLDir;
    reg AnalogRDir;


// Outputs
    wire Len;
    wire Ldir;
    wire Ren;
    wire Rdir;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    Lolhi UUT (
        .A(A), 
        .B(B), 
        .C(C), 
        .AnalogLDir(AnalogLDir), 
        .AnalogRDir(AnalogRDir), 
        .Len(Len), 
        .Ldir(Ldir), 
        .Ren(Ren), 
        .Rdir(Rdir)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
			A = 0; B = 0; C = 0; AnalogLDir = 0; AnalogRDir = 0;
		#10 A = 0; B = 0; C = 0; AnalogLDir = 0; AnalogRDir = 1;
		#10 A = 0; B = 0; C = 0; AnalogLDir = 1; AnalogRDir = 0;
		#10 A = 0; B = 0; C = 0; AnalogLDir = 1; AnalogRDir = 1;
		#10 A = 0; B = 0; C = 1; AnalogLDir = 1; AnalogRDir = 1;
		#10 A = 0; B = 1; C = 0; AnalogLDir = 1; AnalogRDir = 1;
		#10 A = 0; B = 1; C = 1; AnalogLDir = 1; AnalogRDir = 1;
		#10 A = 1; B = 0; C = 0; AnalogLDir = 1; AnalogRDir = 1;
		#10 A = 1; B = 0; C = 1; AnalogLDir = 1; AnalogRDir = 1;
		#10 A = 1; B = 1; C = 0; AnalogLDir = 1; AnalogRDir = 1;
		#10 A = 1; B = 1; C = 1; AnalogLDir = 1; AnalogRDir = 1;
    end

endmodule // Lolhi_tf