

// TOOL:     vlog2tf
// DATE:     Wed May 07 12:26:41 2014
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   section3_schematic
// DESIGN:   section3_schematic
// FILENAME: section3_schematic_tf.v
// PROJECT:  Unknown
// VERSION:  2.0
// This file is auto generated by the Diamond


`timescale 1 ns / 1 ns

// Define Module for Test Fixture
module section3_schematic_tf();

// Inputs
    reg A;
    reg B;
    reg C;
    reg D;



// Outputs
    wire SegA;
    wire SegB;
    wire SegC;
    wire SegD;
    wire SegE;
    wire SegF;
    wire SegG;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    section3_schematic UUT (
        .A(A), 
        .B(B), 
        .C(C), 
        .D(D), 
        .SegA(SegA), 
        .SegB(SegB), 
        .SegC(SegC), 
        .SegD(SegD), 
        .SegE(SegE), 
        .SegF(SegF), 
        .SegG(SegG)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
				A = 0; B = 0; C = 0; D = 0;
			#10 A = 0; B = 0; C = 0; D = 1;
			#10 A = 0; B = 0; C = 1; D = 0;
			#10 A = 0; B = 0; C = 1; D = 1;
			#10 A = 0; B = 1; C = 0; D = 0;
			#10 A = 0; B = 1; C = 0; D = 1;
			#10 A = 0; B = 1; C = 1; D = 0;
			#10 A = 0; B = 1; C = 1; D = 1;
			#10 A = 1; B = 0; C = 0; D = 1;
			#10 A = 1; B = 0; C = 1; D = 0;
			#10 A = 1; B = 0; C = 1; D = 1;
			#10 A = 1; B = 1; C = 0; D = 0;
			#10 A = 1; B = 1; C = 0; D = 1;
			#10 A = 1; B = 1; C = 1; D = 0;
			#10 A = 1; B = 1; C = 1; D = 1;
    end

endmodule // section3_schematic_tf