

// TOOL:     vlog2tf
// DATE:     Wed Apr 23 01:01:02 2014
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   Lab2_TekbotRemote_schematic
// DESIGN:   Lab2_TekbotRemote_schematic
// FILENAME: Lab2_TekbotRemote_schematic_tf.v
// PROJECT:  Unknown
// VERSION:  2.0
// This file is auto generated by the Diamond


`timescale 1 ns / 1 ns

// Define Module for Test Fixture
module Lab2_TekbotRemote_schematic_tf();

// Inputs
    reg A;
    reg B;
    reg C;


// Outputs
    wire Ld;
    wire Le;
    wire Rd;
    wire Re;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    Lab2_TekbotRemote_schematic UUT (
        .A(A), 
        .B(B), 
        .C(C), 
        .Ld(Ld), 
        .Le(Le), 
        .Rd(Rd), 
        .Re(Re)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            A = 0; B = 0; C = 0;
#10 A = 0; B = 0; C = 1;
#10 A = 0; B = 1; C = 0;
#10 A = 0; B = 1; C = 1;
#10 A = 1; B = 0; C = 0;
#10 A = 1; B = 0; C = 1;
#10 A = 1; B = 1; C = 0;
#10 A = 1; B = 1; C = 1;

    end

endmodule // Lab2_TekbotRemote_schematic_tf